import { Pitch, LegacyPitch, User, Profile, Company } from '@/types';

// Mock Profiles (Founders)
export const mockProfiles: Profile[] = [
  {
    id: 'profile-1',
    email: 'sarah@quantumflow.io',
    full_name: 'Sarah Chen',
    username: 'sarahchen',
    avatar_url: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Sarah',
    bio: 'Founder @ QuantumFlow | Ex-Google PM | Supply chain nerd',
    website: 'https://quantumflow.io',
    twitter_handle: '@sarahchen',
    linkedin_url: null,
    followers_count: 342,
    following_count: 128,
    pitches_count: 3,
    companies_count: 1,
    created_at: '2025-09-01T00:00:00Z',
    updated_at: '2025-11-18T10:00:00Z',
  },
  {
    id: 'profile-2',
    email: 'james@medilink.health',
    full_name: 'James Mitchell',
    username: 'jamesmitchell',
    avatar_url: 'https://api.dicebear.com/7.x/avataaars/svg?seed=James',
    bio: 'MD turned founder | Building accessible healthcare',
    website: null,
    twitter_handle: '@jmitchell_md',
    linkedin_url: null,
    followers_count: 189,
    following_count: 92,
    pitches_count: 2,
    companies_count: 1,
    created_at: '2025-09-15T00:00:00Z',
    updated_at: '2025-11-17T15:30:00Z',
  },
  {
    id: 'profile-3',
    email: 'priya@carbonledger.co',
    full_name: 'Priya Patel',
    username: 'priyapatel',
    avatar_url: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Priya',
    bio: 'Climate tech founder | Making carbon credits accessible',
    website: 'https://carbonledger.co',
    twitter_handle: '@priya_climate',
    linkedin_url: null,
    followers_count: 521,
    following_count: 203,
    pitches_count: 3,
    companies_count: 1,
    created_at: '2025-08-20T00:00:00Z',
    updated_at: '2025-11-16T09:15:00Z',
  },
  {
    id: 'profile-4',
    email: 'alex@devsync.dev',
    full_name: 'Alex Turner',
    username: 'alexturner',
    avatar_url: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Alex',
    bio: 'Building the future of remote dev collaboration',
    website: 'https://devsync.dev',
    twitter_handle: '@alexturner',
    linkedin_url: null,
    followers_count: 892,
    following_count: 156,
    pitches_count: 1,
    companies_count: 1,
    created_at: '2025-07-10T00:00:00Z',
    updated_at: '2025-11-15T16:45:00Z',
  },
  {
    id: 'profile-5',
    email: 'nina@finflow.com',
    full_name: 'Nina Rodriguez',
    username: 'ninarodriguez',
    avatar_url: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Nina',
    bio: 'FinTech founder | Ex-Stripe | Solving B2B payments',
    website: 'https://finflow.com',
    twitter_handle: '@nina_finflow',
    linkedin_url: null,
    followers_count: 1203,
    following_count: 287,
    pitches_count: 2,
    companies_count: 1,
    created_at: '2025-08-05T00:00:00Z',
    updated_at: '2025-11-14T13:20:00Z',
  },
  {
    id: 'profile-6',
    email: 'alex@pitchinpublic.com',
    full_name: 'Alex Johnson',
    username: 'alexjohnson',
    avatar_url: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Alex',
    bio: 'Serial founder, AI enthusiast, building in public',
    website: null,
    twitter_handle: null,
    linkedin_url: null,
    followers_count: 1247,
    following_count: 89,
    pitches_count: 3,
    companies_count: 3,
    created_at: '2024-08-15T00:00:00Z',
    updated_at: '2025-11-20T09:00:00Z',
  },
];

// Mock Companies
export const mockCompanies: Company[] = [
  {
    id: 'company-1',
    founder_id: 'profile-1',
    name: 'QuantumFlow',
    slug: 'quantumflow',
    tagline: 'AI-powered supply chain optimization',
    description: 'We use machine learning to predict supply chain disruptions before they happen, automatically rerouting shipments and optimizing inventory across warehouses.',
    industry: 'AI/ML',
    stage: 'Seed',
    website: 'https://quantumflow.io',
    twitter_handle: '@quantumflow',
    linkedin_url: null,
    pitches_count: 3,
    total_views: 12400,
    total_roasts: 23,
    total_toasts: 89,
    status: 'active',
    created_at: '2025-09-01T00:00:00Z',
    updated_at: '2025-11-18T10:00:00Z',
  },
  {
    id: 'company-2',
    founder_id: 'profile-2',
    name: 'MediLink',
    slug: 'medilink',
    tagline: 'Telemedicine for rural America',
    description: 'Rural healthcare deserts affect 20% of Americans. MediLink uses AI triage to instantly match patients with the right specialist, reducing wait times from weeks to seconds.',
    industry: 'HealthTech',
    stage: 'Pre-Seed',
    website: null,
    twitter_handle: '@medilink_health',
    linkedin_url: null,
    pitches_count: 2,
    total_views: 8900,
    total_roasts: 15,
    total_toasts: 67,
    status: 'active',
    created_at: '2025-09-15T00:00:00Z',
    updated_at: '2025-11-17T15:30:00Z',
  },
  {
    id: 'company-3',
    founder_id: 'profile-3',
    name: 'CarbonLedger',
    slug: 'carbonledger',
    tagline: 'Blockchain-verified carbon credits for SMBs',
    description: 'Small businesses want to go carbon neutral but carbon credit markets are opaque and expensive. We verify credits on-chain and offer fractional purchases starting at $10/month.',
    industry: 'Climate',
    stage: 'Seed',
    website: 'https://carbonledger.co',
    twitter_handle: '@carbonledger',
    linkedin_url: null,
    pitches_count: 3,
    total_views: 15600,
    total_roasts: 42,
    total_toasts: 78,
    status: 'active',
    created_at: '2025-08-20T00:00:00Z',
    updated_at: '2025-11-16T09:15:00Z',
  },
  {
    id: 'company-4',
    founder_id: 'profile-4',
    name: 'DevSync',
    slug: 'devsync',
    tagline: 'Real-time collaborative IDE for distributed teams',
    description: 'Remote teams waste 2 hours daily on async code reviews and merge conflicts. DevSync lets teams code together in real-time with AI-powered conflict resolution.',
    industry: 'SaaS',
    stage: 'Series A',
    website: 'https://devsync.dev',
    twitter_handle: '@devsync',
    linkedin_url: null,
    pitches_count: 1,
    total_views: 22100,
    total_roasts: 31,
    total_toasts: 134,
    status: 'active',
    created_at: '2025-07-10T00:00:00Z',
    updated_at: '2025-11-15T16:45:00Z',
  },
  {
    id: 'company-5',
    founder_id: 'profile-5',
    name: 'FinFlow',
    slug: 'finflow',
    tagline: 'Stripe for B2B payments',
    description: 'B2B sellers lose deals because they can\'t offer net-60 terms. FinFlow provides instant payouts while letting buyers pay later, taking a 2.9% fee.',
    industry: 'FinTech',
    stage: 'Seed',
    website: 'https://finflow.com',
    twitter_handle: '@finflow',
    linkedin_url: null,
    pitches_count: 2,
    total_views: 18300,
    total_roasts: 28,
    total_toasts: 102,
    status: 'active',
    created_at: '2025-08-05T00:00:00Z',
    updated_at: '2025-11-14T13:20:00Z',
  },
  {
    id: 'company-6',
    founder_id: 'profile-6',
    name: 'PitchFlow AI',
    slug: 'pitchflow-ai',
    tagline: 'AI coach for investor pitches',
    description: 'Founders spend weeks perfecting their pitch. PitchFlow AI analyzes your pitch video, identifies weaknesses, and suggests improvements using GPT-4.',
    industry: 'AI/ML',
    stage: 'Pre-Seed',
    website: null,
    twitter_handle: null,
    linkedin_url: null,
    pitches_count: 1,
    total_views: 8700,
    total_roasts: 12,
    total_toasts: 45,
    status: 'active',
    created_at: '2025-10-15T00:00:00Z',
    updated_at: '2025-11-20T09:00:00Z',
  },
  {
    id: 'company-7',
    founder_id: 'profile-6',
    name: 'NomadHub',
    slug: 'nomadhub',
    tagline: 'Airbnb for digital nomads',
    description: 'Digital nomads waste time finding wifi, desks, and community in each city. NomadHub offers curated stays with guaranteed fast wifi, desk space, and local nomad events.',
    industry: 'Consumer',
    stage: 'Seed',
    website: null,
    twitter_handle: null,
    linkedin_url: null,
    pitches_count: 1,
    total_views: 15200,
    total_roasts: 18,
    total_toasts: 72,
    status: 'active',
    created_at: '2025-09-05T00:00:00Z',
    updated_at: '2025-11-10T14:30:00Z',
  },
  {
    id: 'company-8',
    founder_id: 'profile-6',
    name: 'CodeMentor Pro',
    slug: 'codementor-pro',
    tagline: 'On-demand senior engineers for code reviews',
    description: 'Junior devs get stuck for hours on problems a senior could solve in minutes. CodeMentor Pro connects you with vetted senior engineers for quick code reviews and pair programming.',
    industry: 'SaaS',
    stage: 'Pre-Seed',
    website: null,
    twitter_handle: null,
    linkedin_url: null,
    pitches_count: 1,
    total_views: 6400,
    total_roasts: 8,
    total_toasts: 31,
    status: 'active',
    created_at: '2025-09-20T00:00:00Z',
    updated_at: '2025-10-25T11:15:00Z',
  },
];

// Mock current user (legacy)
export const mockUser: User = {
  id: 'profile-6',
  name: 'Alex Johnson',
  email: 'alex@pitchinpublic.com',
  avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Alex',
  bio: 'Serial founder, AI enthusiast, building in public',
  followersCount: 1247,
  followingCount: 89,
  pitchesCount: 3,
  createdAt: '2024-08-15T00:00:00Z',
};

// Mock Pitches (new database schema)
export const mockPitches: Pitch[] = [
  {
    id: 'pitch-1',
    user_id: 'profile-1',
    company_id: 'company-1',
    hook: 'AI-powered supply chain optimization that saves manufacturers 40% on logistics',
    description: 'We use machine learning to predict supply chain disruptions before they happen, automatically rerouting shipments and optimizing inventory across warehouses.',
    video_url: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/BigBuckBunny.mp4',
    video_provider: 'cloudflare',
    video_id: null,
    thumbnail_url: 'https://images.unsplash.com/photo-1586528116311-ad8dd3c8310d?w=800&q=80',
    duration: 60,
    version_number: 3,
    views_count: 12400,
    roast_count: 23,
    toast_count: 89,
    interest_score: 87,
    status: 'published',
    created_at: '2025-11-18T10:00:00Z',
    updated_at: '2025-11-19T14:30:00Z',
    company: mockCompanies[0],
    founder: mockProfiles[0],
  },
  {
    id: 'pitch-2',
    user_id: 'profile-2',
    company_id: 'company-2',
    hook: 'Telemedicine platform connecting rural patients with specialists in under 60 seconds',
    description: 'Rural healthcare deserts affect 20% of Americans. MediLink uses AI triage to instantly match patients with the right specialist, reducing wait times from weeks to seconds.',
    video_url: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ElephantsDream.mp4',
    video_provider: 'cloudflare',
    video_id: null,
    thumbnail_url: 'https://images.unsplash.com/photo-1576091160399-112ba8d25d1d?w=800&q=80',
    duration: 58,
    version_number: 2,
    views_count: 8900,
    roast_count: 15,
    toast_count: 67,
    interest_score: 79,
    status: 'published',
    created_at: '2025-11-17T15:30:00Z',
    updated_at: '2025-11-17T15:30:00Z',
    company: mockCompanies[1],
    founder: mockProfiles[1],
  },
  {
    id: 'pitch-3',
    user_id: 'profile-3',
    company_id: 'company-3',
    hook: 'Blockchain-verified carbon credits marketplace for SMBs',
    description: 'Small businesses want to go carbon neutral but carbon credit markets are opaque and expensive. We verify credits on-chain and offer fractional purchases starting at $10/month.',
    video_url: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/Sintel.mp4',
    video_provider: 'cloudflare',
    video_id: null,
    thumbnail_url: 'https://images.unsplash.com/photo-1569163139394-de4798aa62b6?w=800&q=80',
    duration: 45,
    version_number: 3,
    views_count: 15600,
    roast_count: 42,
    toast_count: 78,
    interest_score: 82,
    status: 'published',
    created_at: '2025-11-16T09:15:00Z',
    updated_at: '2025-11-17T11:20:00Z',
    company: mockCompanies[2],
    founder: mockProfiles[2],
  },
  {
    id: 'pitch-4',
    user_id: 'profile-4',
    company_id: 'company-4',
    hook: 'Real-time collaborative IDE for distributed engineering teams, 10x faster than GitHub',
    description: 'Remote teams waste 2 hours daily on async code reviews and merge conflicts. DevSync lets teams code together in real-time with AI-powered conflict resolution.',
    video_url: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/TearsOfSteel.mp4',
    video_provider: 'cloudflare',
    video_id: null,
    thumbnail_url: 'https://images.unsplash.com/photo-1555066931-4365d14bab8c?w=800&q=80',
    duration: 52,
    version_number: 1,
    views_count: 22100,
    roast_count: 31,
    toast_count: 134,
    interest_score: 91,
    status: 'published',
    created_at: '2025-11-15T16:45:00Z',
    updated_at: '2025-11-16T14:30:00Z',
    company: mockCompanies[3],
    founder: mockProfiles[3],
  },
  {
    id: 'pitch-5',
    user_id: 'profile-5',
    company_id: 'company-5',
    hook: 'Stripe for B2B payments - net-60 terms without the cash flow pain',
    description: 'B2B sellers lose deals because they can\'t offer net-60 terms. FinFlow provides instant payouts while letting buyers pay later, taking a 2.9% fee.',
    video_url: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/SubaruOutbackOnStreetAndDirt.mp4',
    video_provider: 'cloudflare',
    video_id: null,
    thumbnail_url: 'https://images.unsplash.com/photo-1554224155-8d04cb21cd6c?w=800&q=80',
    duration: 47,
    version_number: 2,
    views_count: 18300,
    roast_count: 28,
    toast_count: 102,
    interest_score: 88,
    status: 'published',
    created_at: '2025-11-14T13:20:00Z',
    updated_at: '2025-11-15T09:45:00Z',
    company: mockCompanies[4],
    founder: mockProfiles[4],
  },
  {
    id: 'pitch-6',
    user_id: 'profile-6',
    company_id: 'company-6',
    hook: 'AI coach that turns rambling pitches into investor-ready narratives in 60 seconds',
    description: 'Founders spend weeks perfecting their pitch. PitchFlow AI analyzes your pitch video, identifies weaknesses, and suggests improvements using GPT-4.',
    video_url: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/BigBuckBunny.mp4',
    video_provider: 'cloudflare',
    video_id: null,
    thumbnail_url: 'https://images.unsplash.com/photo-1531482615713-2afd69097998?w=800&q=80',
    duration: 58,
    version_number: 1,
    views_count: 8700,
    roast_count: 12,
    toast_count: 45,
    interest_score: 78,
    status: 'published',
    created_at: '2025-11-20T09:00:00Z',
    updated_at: '2025-11-20T09:00:00Z',
    company: mockCompanies[5],
    founder: mockProfiles[5],
  },
  {
    id: 'pitch-7',
    user_id: 'profile-6',
    company_id: 'company-7',
    hook: 'Airbnb for digital nomads with built-in coworking and community',
    description: 'Digital nomads waste time finding wifi, desks, and community in each city. NomadHub offers curated stays with guaranteed fast wifi, desk space, and local nomad events.',
    video_url: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ElephantsDream.mp4',
    video_provider: 'cloudflare',
    video_id: null,
    thumbnail_url: 'https://images.unsplash.com/photo-1522202176988-66273c2fd55f?w=800&q=80',
    duration: 55,
    version_number: 1,
    views_count: 15200,
    roast_count: 18,
    toast_count: 72,
    interest_score: 84,
    status: 'published',
    created_at: '2025-11-10T14:30:00Z',
    updated_at: '2025-11-10T14:30:00Z',
    company: mockCompanies[6],
    founder: mockProfiles[5],
  },
  {
    id: 'pitch-8',
    user_id: 'profile-6',
    company_id: 'company-8',
    hook: 'On-demand senior engineers for code reviews, $99/hour flat rate',
    description: 'Junior devs get stuck for hours on problems a senior could solve in minutes. CodeMentor Pro connects you with vetted senior engineers for quick code reviews and pair programming.',
    video_url: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/Sintel.mp4',
    video_provider: 'cloudflare',
    video_id: null,
    thumbnail_url: 'https://images.unsplash.com/photo-1517694712202-14dd9538aa97?w=800&q=80',
    duration: 48,
    version_number: 1,
    views_count: 6400,
    roast_count: 8,
    toast_count: 31,
    interest_score: 72,
    status: 'published',
    created_at: '2025-10-25T11:15:00Z',
    updated_at: '2025-10-25T11:15:00Z',
    company: mockCompanies[7],
    founder: mockProfiles[5],
  }
];

// Helper function to convert new Pitch to LegacyPitch for backwards compatibility
export function toLegacyPitch(pitch: Pitch): LegacyPitch {
  return {
    id: pitch.id,
    userId: pitch.user_id,
    founderName: pitch.founder?.full_name || 'Unknown',
    founderAvatar: pitch.founder?.avatar_url || 'https://api.dicebear.com/7.x/avataaars/svg?seed=Unknown',
    companyName: pitch.company?.name || 'Unknown Company',
    hook: pitch.hook,
    description: pitch.description || '',
    videoUrl: pitch.video_url,
    thumbnailUrl: pitch.thumbnail_url || '',
    industry: pitch.company?.industry || 'SaaS',
    stage: pitch.company?.stage || 'Pre-Seed',
    views: pitch.views_count,
    interestScore: pitch.interest_score / 10, // Convert back to decimal
    roastCount: pitch.roast_count,
    toastCount: pitch.toast_count,
    createdAt: pitch.created_at,
    duration: pitch.duration || undefined,
    // Feedback conversion would be needed if pitch.feedback is populated
    // For now, set to undefined as mock data doesn't include feedback
    feedback: undefined,
  };
}

// Helper functions
export function getPitchById(id: string): Pitch | undefined {
  return mockPitches.find(pitch => pitch.id === id);
}

export function getRecentPitches(limit: number = 10): Pitch[] {
  return [...mockPitches]
    .sort((a, b) => new Date(b.created_at).getTime() - new Date(a.created_at).getTime())
    .slice(0, limit);
}

// Legacy functions for backwards compatibility
export function getLegacyPitches(): LegacyPitch[] {
  return mockPitches.map(toLegacyPitch);
}

export function getLegacyPitchById(id: string): LegacyPitch | undefined {
  const pitch = getPitchById(id);
  return pitch ? toLegacyPitch(pitch) : undefined;
}

export function getRecentLegacyPitches(limit: number = 10): LegacyPitch[] {
  return getRecentPitches(limit).map(toLegacyPitch);
}

// Helper to get company by slug
export function getCompanyBySlug(slug: string): Company | undefined {
  return mockCompanies.find(company => company.slug === slug);
}

// Helper to get company pitches
export function getCompanyPitches(companyId: string): Pitch[] {
  return mockPitches
    .filter(pitch => pitch.company_id === companyId)
    .sort((a, b) => b.version_number - a.version_number);
}

// Helper to get profile by username
export function getProfileByUsername(username: string): Profile | undefined {
  return mockProfiles.find(profile => profile.username === username);
}

// Helper to convert Profile (database type) to User (legacy type)
export function profileToUser(profile: Profile): User {
  return {
    id: profile.id,
    publicHandle: profile.public_handle || profile.username || null,
    name: profile.full_name,
    email: profile.email,
    avatar: profile.avatar_url || `https://api.dicebear.com/7.x/avataaars/svg?seed=${encodeURIComponent(profile.full_name)}`,
    bio: profile.bio || undefined,
    followersCount: profile.followers_count,
    followingCount: profile.following_count,
    pitchesCount: profile.pitches_count,
    createdAt: profile.created_at,
  };
}

// Helper to create a User from Supabase auth User object
export function authUserToUser(authUser: any): User {
  const name = authUser.user_metadata?.full_name || authUser.email?.split('@')[0] || 'User';
  return {
    id: authUser.id,
    name: name,
    email: authUser.email || 'unknown@example.com',
    avatar: authUser.user_metadata?.avatar_url || `https://api.dicebear.com/7.x/avataaars/svg?seed=${encodeURIComponent(name)}`,
    bio: authUser.user_metadata?.bio || undefined,
    followersCount: 0,
    followingCount: 0,
    pitchesCount: 0,
    createdAt: authUser.created_at || new Date().toISOString(),
  };
}
